### ISSUE TITLE
Fix Settings

### ISSUE THREAD

**Issue by EnzoBonato** [astrodevs-labs/osmium-solidity#120]
### Title

Fix Settings

### Description

Fix the following bugs: 
settings: tests feature is not disabled
settings: disabled -> reenable the sidebar does not work 
settings: formatter works even if disabled (even after restart)    

### Expected behavior

Settings fixed

### Steps to reproduce

- [ ] 1. 
- [ ] 2. 
- [ ] 3.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jjyutm4532** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change addresses three settings-related bugs:
1. Disables the tests feature when the setting is turned off
2. Allows re-enabling the sidebar after it has been disabled
3. Ensures the formatter is disabled when its setting is turned off, even after restart

You can review changes in this commit: https://github.com/jjyutm4532/astrodevs-labs-osmium-solidity-120/commit/4f6df7a822affeddf446abedcb15100a35f42dd8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
