### ISSUE TITLE
Refactor definition

### ISSUE THREAD

**Issue by 0xmemorygrinder** [astrodevs-labs/osmium-solidity#49]
### Description

Allow the user to use the "rename/refactor" feature on a definition to rename all the references of a variable or function

### As

solidity developer

### I want to

Be able to rename definitions

### Definition of Done

- [ ] The user is able to use the F2 shortcut on definitions
- [ ] All the references get renamed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xSwapFeeder** [comment]
@0xmemorygrinder to be closed ?
