### ISSUE TITLE
Interact infinite loading

### ISSUE THREAD

**Issue by 0xmemorygrinder** [astrodevs-labs/osmium-solidity#66]
### Title

Interact infinite loading

### Description

When using the interact feature in the sidebar, some call infinitely load (active spinner) without ever finishing.

A timeout and better error management should be implemented

### Expected behavior

An infinite loading should never occur

### Steps to reproduce

- [ ] Launch the extension
- [ ] Open the sidebar
- [ ] Interact with a contract

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ByFishh** [comment]
Can't reproduce
